[project]
name = "LedFx"
version = "2.2.0"

[tool.release-ci]
github-distributions = false
assets = [
    "LedFx-{tag_version}-win-x64.zip",
    "LedFx-{tag_version}-win-x64-setup.zip",
    "LedFx-{tag_version}-osx-arm64.tar.gz",
    "LedFx-{tag_version}-osx-intel.tar.gz",
]

[[tool.release-ci.oci]]
image = "ghcr.io/ledfx/ledfx"
platforms = ["linux/amd64", "linux/arm64"]
promote-latest = true

[[tool.release-ci.oci]]
image = "docker.io/ledfxorg/ledfx"
platforms = ["linux/amd64", "linux/arm64"]
promote-latest = true
